//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events_TenantUserApp.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketId { get; set; }
        public int RowNumber { get; set; }
        public int SeatNumber { get; set; }
        public int EventId { get; set; }
        public int SectionId { get; set; }
        public int TicketPurchaseId { get; set; }
    
        public virtual EventSections EventSections { get; set; }
        public virtual TicketPurchases TicketPurchases { get; set; }
    }
}
