//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events_TenantUserApp.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VenueTypes()
        {
            this.Venues = new HashSet<Venues>();
        }
    
        public string VenueType { get; set; }
        public string VenueTypeName { get; set; }
        public string EventTypeName { get; set; }
        public string EventTypeShortName { get; set; }
        public string EventTypeShortNamePlural { get; set; }
        public string Language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venues> Venues { get; set; }
    }
}
