//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events_TenantUserApp.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venues
    {
        public string VenueName { get; set; }
        public string VenueType { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPassword { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual VenueTypes VenueTypes { get; set; }
    }
}
